---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: OperatingSystemConfig
metadata:
  name: pool-01-original
  namespace: default
spec:
  type: metal
  purpose: provision
  units:
  - name: docker.service
    dropIns:
    - name: 10-docker-opts.conf
      content: |
        [Service]
        Environment="DOCKER_OPTS=--log-opt max-size=60m --log-opt max-file=3"
  - name: docker-monitor.service
    command: start
    enable: true
    content: |
      [Unit]
      Description=Docker-monitor daemon
      After=kubelet.service
      [Install]
      WantedBy=multi-user.target
      [Service]
      Restart=always
      EnvironmentFile=/etc/environment
      ExecStart=/opt/bin/health-monitor docker
  - name: gardener-cc.service
    enable: true
    content: |
      [Unit]
      Description=gardener-cloud-config reconfiguration
      [Service]
      ExecStart=-/var/lib/cloud-config-downloader/download-cloud-config.sh
      [Install]
      WantedBy=multi-user.target
  - name: gardener-cc.timer
    enable: true
    content: |
      [Unit]
      Description=gardener-cloud-config reconfiguration periodic restart
      [Timer]
      OnBootSec=60sec
      OnCalendar=*:*:01
      [Install]
      WantedBy=timers.target
  files:
  - path: /var/lib/kubelet/ca.crt
    permissions: 0644
    content:
      inline:
        encoding: ""
        data: |
          Hello World
  - path: /etc/sysctl.d/99-k8s-general.conf
    permissions: 0644
    content:
      inline:
        encoding: ""
        data: |
          # A higher vm.max_map_count is great for elasticsearch, mongo, or other mmap users
          # See https://github.com/kubernetes/kops/issues/1340
          vm.max_map_count = 135217728
