apiVersion: apps/v1
kind: Deployment
metadata:
  name: gardener-extension-os-metal
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-os-metal
    helm.sh/chart: gardener-extension-os-metal
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gardener-extension-os-metal
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gardener-extension-os-metal
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: gardener-extension-os-metal
      containers:
      - name: gardener-extension-os-metal
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /os-metal
        - --leader-election-resource-lock={{ .Values.leaderElection.resourceLock }}
        - --max-concurrent-reconciles={{ .Values.controllers.concurrentSyncs }}
        - --heartbeat-namespace={{ .Release.Namespace }}
        - --heartbeat-renew-interval-seconds={{ .Values.controllers.heartbeat.renewIntervalSeconds }}
        - --disable-controllers={{ .Values.disableControllers | join "," }}
        - --ignore-operation-annotation={{ .Values.controllers.ignoreOperationAnnotation }}
        env:
        - name: LEADER_ELECTION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
