name: Docker Image from pull request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go 1.21
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"
      id: go

    - name: Figure out if running fork PR
      id: fork
      run: '["${{ secrets.DOCKER_REGISTRY_TOKEN }}" == ""] && echo "::set-output name=is_fork_pr::true" || echo "::set-output name=is_fork_pr::false"'

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      if: steps.fork.outputs.is_fork_pr == 'false'

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: -p bugs --timeout=10m

    - name: Build
      run: |
        export GITHUB_TAG_NAME=${GITHUB_HEAD_REF##*/}
        make docker-image
    - name: Push
      run: |
        export GITHUB_TAG_NAME=${GITHUB_HEAD_REF##*/}
        make docker-push
      if: steps.fork.outputs.is_fork_pr == 'false'
